language: cpp
dist: trusty
python:
  - 3.5
compiler:
  - clang
  - gcc

script: make && make test


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    #- gcc-4.8
    - g++-4.8
    - clang



# attempt to install python3 manually
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - python3 -V
  - pip3 -V
  - pip3 install pytest
