language: python
python:
  - 3.5

#install:
#  sudo apt-get install -qq gcc-4.8 g++

script: make && make test


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
