language: cpp
dist: trusty
python:
  - 3.5
compiler:
  - clang
  - gcc

script: make && make test


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - clang

# install python3 manually (in cpp language set up)
before_install:
  - sudo apt-get -y install python3-pip python-dev valgrind
  - sudo pip3 install -U setuptools
  - python3 -V
  - pip3 -V
  - pip3 install pytest
  - valgrind --version
